[HeaderNumber]
0
*****
[KeyOptions]
100
0
(if p(v940) then if v940^a:'6' then if v940^v=&unifor('Av991#1') then if p(v940^w)then else '^aB=',if p(v940^b) then if v940^b.1='0'or val(v940^b.1)>0 then f(val(v940^b,' 0'),8,0) else v940^b.1,   if v940^b*1 <>''then f(val(v940^b*1),7,0) fi fi else f(val(v940^h,' 0'),8,0) fi fi fi fi fi/),(if p(v940)then if v940^v=&unifor('Av991#1') then if v940^a:'6' then else if val(v940^x,' 0')-val(v940^z,' 0') >0 then '^aB=',if p(v940^b) then if v940^b.1='0'or val(v940^b.1)>0 then f(val(v940^b,' 0'),8,0) else v940^b.1,if v940^b*1 <>''then f(val(v940^b*1),7,0) fi fi else f(val(v940^h,' 0'),8,0) fi, fi fi fi fi/)
*****
