[HeaderNumber]
0
*****
[KeyOptions]
300
0
if rsum((if p(v910) then if '2 6 7':v910 then else if s(v910^y,v910^u)<>''then if (&unifor('Av991^a#1')<>''and &uf('G0-'&uf('G2-'&unifor('Av991^a#1')))=v910^y and v910^u*2.2=&uf('G0-'&uf('Av991^a#1')))or(&uf('Av991^a#1')=''and &unifor('Av991^b#1')=v910^u ) then'1; 'else'0;'fi fi fi fi))>0 then ( if p(v910)then if  &uf('G0-'&uf('G2-'&unifor('Av991^a#1')))=v910^y and &uf('Av991^a#1')<>'' or &uf('Av991^b#1')=v910^u and &uf('Av991^a#1')=''then if v910^b<>''then '^AB='if v910^b.1='0'or val(v910^b.1)>0 then f(val(v910^b.1),8,0) else v910^b.1,f(val(v910^b*1),7,0) fi else v910^h fi fi fi )fi 
*****
