[HeaderNumber]
0
*****
[KeyOptions]
10
0
if s(v215^y)=''then if rsum((if p(v910) then if '2 7':v910^a or p(v910^4) then else if &unifor('Av991^b#1')<>'' and &unifor('Av991^b#1')=v910^d or &unifor('Av991^b#1') ='' then '1;' else'0;' fi fi fi))>0 then '^aB='if &unifor('Av910^b#1')<>''then if &unifor('Av910^b.1#1')='0'or val(&unifor('Av910^b.1#1'))>0 then f(val(&unifor('Av910^b#1'),' 0'),8,0)else &unifor('Av910^b.1#1'),f(val(&unifor('Av910^b*1#1')),7,0)fi else &unifor('Av910^h#1') fi fi fi/
*****
