[HeaderNumber]
0
*****

[KeyOptions]
200
1
if rsum((if p(v62) then if a(v62^g) then if v62^b=&unifor('Av991^b*1#1') then '1;'else '0;'fi fi else '0;'fi /))>0 then v461^x,v700^a,v461^c,v200^v,v200^a fi, if p(v30^u)then else if v991^a=v30^k then v461^x,v700^a,v461^c,v200^v,v200^a fi fi,if p(v31^u)then else if v991^a=v31^k then v461^x,v700^a,v461^c,v200^v,v200^a fi fi,if p(v32^u)then else if v991^a=v32^k then v461^x,v700^a,v461^c,v200^v,v200^a fi fi
*****
