[HeaderNumber]
0
*****

[KeyOptions]
100
0
if rsum((if p(v910) then if '2 6':v910 then else if s(v910^y,v910^u)<>''then if (&unifor('G0+'&unifor('Av991^a#1'))=v910^y or &unifor('Av991^a#1')='')and (&unifor('Av991^b#1')=v910^u or &unifor('Av991^b#1')='') then'1; 'else'0;'fi fi fi fi))>0 then if &unifor('Av910^b#1')<>'' then'^AB='if &unifor('Av910^b.1#1')='0'or val(&unifor('Av910^b.1#1'))>0 then f(val(&unifor('Av910^b.1#1')),8,0) else &unifor('Av910^b.1#1'),f(val(&unifor('Av910^b*1#1')),7,0) fi else &unifor('Av910^h#1') fi fi 
*****
