[HeaderNumber]
0
*****

[KeyOptions]
10
0
if p(v910) then if s(v215^y)=''then (if p(v910) then if 'C U 2 7':v910^a then else if &unifor('Av991#1')<>'' then if (&unifor('Av991^a#1')<>'' and v910^u=&unifor('Av991^a#1') or &unifor('Av991^a#1')='') and (&unifor('Av991^b#1')<>'' and v910^d=&unifor('Av991^b#1') or &unifor('Av991^b#1')='') then '^aB='if &unifor('Av910^b#1')<>''then if &unifor('Av910^b.1#1')='0'or val(&unifor('Av910^b.1#1'))>0 then f(val(&unifor('Av910^b#1'),' 0'),8,0) else &unifor('Av910^b.1#1'),f(val(&unifor('Av910^b*1#1')),7,0) fi else &unifor('Av910^h#1') fi fi fi fi fi/) fi fi
*****
